// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbfikadeedkgodfdgjnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZmlrYWRlZWRrZ29kZmRnam5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwOTcyMDMsImV4cCI6MjA4MDY3MzIwM30.h-eDu5zrl8BYuv8TEw7pY9PD11oBD5aaJtFcwHQcZfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});